# Generated by Django 2.0.1 on 2020-12-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201204_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedfood',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='food/feed'),
        ),
    ]
