# Generated by Django 2.0.1 on 2021-01-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20201204_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrun',
            name='execution_date',
            field=models.DateTimeField(null=True),
        ),
    ]
