# Generated by Django 2.0.1 on 2021-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodrun_execution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrun',
            name='invitation_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
