# Generated by Django 2.0.1 on 2020-02-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200206_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homelessprofile',
            old_name='user',
            new_name='userRegisterer',
        ),
    ]
