# Generated by Django 2.0.1 on 2020-02-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200206_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelessprofile',
            name='aboutYou',
            field=models.TextField(blank=True, null=True),
        ),
    ]
