# Generated by Django 2.0.1 on 2020-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200211_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
