# Generated by Django 2.0.1 on 2020-10-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201013_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelessprofile',
            name='location_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homelessprofile',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
    ]
