# Generated by Django 2.0.1 on 2020-11-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201017_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelessprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
