# Generated by Django 2.0.1 on 2020-11-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_homelessprofile_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelessprofile',
            name='qr_code',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
