# Generated by Django 2.0.1 on 2021-01-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201125_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelessprofile',
            name='code',
            field=models.SlugField(max_length=15, null=True, unique=True),
        ),
    ]
