# Generated by Django 2.0.1 on 2020-10-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentfeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentfeed',
            old_name='fedd',
            new_name='feed',
        ),
    ]
