# Generated by Django 2.0.1 on 2020-10-31 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='details',
        ),
    ]
