# Generated by Django 2.0.1 on 2020-11-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20201125_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='rest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cause',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='donation',
            name='mount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
