# Generated by Django 2.0.1 on 2020-11-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20201125_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='mount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='cause',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=6, null=True),
        ),
    ]
